#!/bin/bash

# source: http://blog.andresgomez.org/2014/11/19/switching-between-nouveau-and-the-nvidia-proprietary-opengl-driver-in-debian-gnulinux/

ALTERNATIVE=""

function check_root {
    ID=`id -u`
    if [ ${ID} -ne 0 ]; then
        echo "You have to be root to run this script"
        exit 0
    fi
}

function syntax {
    echo "Syntax: $0 [nvidia|nouveau]"
    exit 0
}

function set_nouveau {
    rm -f /etc/modprobe.d/nvidia-blacklists-nouveau.conf
    echo "blacklist nvidia" > /etc/modprobe.d/nouveau-blacklists-nvidia.conf
    # This doesn't really seem to be needed any more
#    echo 'Section "Device"
#    Identifier     "Device0"
#    Driver         "nouveau"
#EndSection
#' > /usr/share/X11/xorg.conf.d/20-nouveau.conf
    rm -f /etc/X11/xorg.conf
    ALTERNATIVE="/usr/lib/mesa-diverted"
}

function set_nvidia {
    rm -f /etc/modprobe.d/nouveau-blacklists-nvidia.conf
    ln -s /etc/nvidia/nvidia-blacklists-nouveau.conf /etc/modprobe.d/nvidia-blacklists-nouveau.conf
    # This doesn't really seem to be needed any more
    # rm -f /usr/share/X11/xorg.conf.d/20-nouveau.conf
    # This is the output generated by nvidia-xconfig in my system
    # Customize appropriately for your system
    echo '# nvidia-xconfig: X configuration file generated by nvidia-xconfig
# nvidia-xconfig:  version 340.46  (buildd@brahms)  Tue Oct  7 08:00:32 UTC 2014

Section "ServerLayout"
    Identifier     "Layout0"
    Screen      0  "Screen0"
    InputDevice    "Keyboard0" "CoreKeyboard"
    InputDevice    "Mouse0" "CorePointer"
EndSection

Section "Files"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Mouse0"
    Driver         "mouse"
    Option         "Protocol" "auto"
    Option         "Device" "/dev/psaux"
    Option         "Emulate3Buttons" "no"
    Option         "ZAxisMapping" "4 5"
EndSection

Section "InputDevice"
    # generated from default
    Identifier     "Keyboard0"
    Driver         "kbd"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 33.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
    EndSubSection
EndSection
' > /etc/X11/xorg.conf
    ALTERNATIVE="/usr/lib/nvidia"
}

check_root

if [ -z "${1}" ]; then
    syntax
elif [ "x${1}" == "xnouveau" ]; then
    set_nouveau
elif [ "x${1}" == "xnvidia" ]; then
    set_nvidia
else
    syntax
fi

update-alternatives --set glx "${ALTERNATIVE}"
update-initramfs -u

echo ""
echo "${1} successfully set. Reboot your system to apply the changes ..."
